#pragma once

#define PKE_KEY_None PurrKatEngine::KeyCode::None
#define PKE_KEY_Tab PurrKatEngine::KeyCode::Tab
#define PKE_KEY_Space PurrKatEngine::KeyCode::Space
#define PKE_KEY_Enter PurrKatEngine::KeyCode::Enter
#define PKE_KEY_Escape PurrKatEngine::KeyCode::Escape
#define PKE_KEY_LeftArrow PurrKatEngine::KeyCode::LeftArrow
#define PKE_KEY_RightArrow PurrKatEngine::KeyCode::RightArrow
#define PKE_KEY_UpArrow PurrKatEngine::KeyCode::UpArrow
#define PKE_KEY_DownArrow PurrKatEngine::KeyCode::DownArrow
#define PKE_KEY_PageUp PurrKatEngine::KeyCode::PageUp
#define PKE_KEY_PageDown PurrKatEngine::KeyCode::PageDown
#define PKE_KEY_Home PurrKatEngine::KeyCode::Home
#define PKE_KEY_End PurrKatEngine::KeyCode::End
#define PKE_KEY_Insert PurrKatEngine::KeyCode::Insert
#define PKE_KEY_Delete PurrKatEngine::KeyCode::Delete
#define PKE_KEY_Backspace PurrKatEngine::KeyCode::Backspace
#define PKE_KEY_LeftCtrl PurrKatEngine::KeyCode::LeftCtrl
#define PKE_KEY_LeftShift PurrKatEngine::KeyCode::LeftShift
#define PKE_KEY_LeftAlt PurrKatEngine::KeyCode::LeftAlt
#define PKE_KEY_LeftSuper PurrKatEngine::KeyCode::LeftSuper
#define PKE_KEY_RightCtrl PurrKatEngine::KeyCode::RightCtrl
#define PKE_KEY_RightShift PurrKatEngine::KeyCode::RightShift
#define PKE_KEY_RightAlt PurrKatEngine::KeyCode::RightAlt
#define PKE_KEY_RightSuper PurrKatEngine::KeyCode::RightSuper
#define PKE_KEY_Menu PurrKatEngine::KeyCode::Menu
#define PKE_KEY_Key0 PurrKatEngine::KeyCode::Key0
#define PKE_KEY_Key1 PurrKatEngine::KeyCode::Key1
#define PKE_KEY_Key2 PurrKatEngine::KeyCode::Key2
#define PKE_KEY_Key3 PurrKatEngine::KeyCode::Key3
#define PKE_KEY_Key4 PurrKatEngine::KeyCode::Key4
#define PKE_KEY_Key5 PurrKatEngine::KeyCode::Key5
#define PKE_KEY_Key6 PurrKatEngine::KeyCode::Key6
#define PKE_KEY_Key7 PurrKatEngine::KeyCode::Key7
#define PKE_KEY_Key8 PurrKatEngine::KeyCode::Key8
#define PKE_KEY_Key9 PurrKatEngine::KeyCode::Key9
#define PKE_KEY_A PurrKatEngine::KeyCode::A
#define PKE_KEY_B PurrKatEngine::KeyCode::B
#define PKE_KEY_C PurrKatEngine::KeyCode::C
#define PKE_KEY_D PurrKatEngine::KeyCode::D
#define PKE_KEY_E PurrKatEngine::KeyCode::E
#define PKE_KEY_F PurrKatEngine::KeyCode::F
#define PKE_KEY_G PurrKatEngine::KeyCode::G
#define PKE_KEY_H PurrKatEngine::KeyCode::H
#define PKE_KEY_I PurrKatEngine::KeyCode::I
#define PKE_KEY_J PurrKatEngine::KeyCode::J
#define PKE_KEY_K PurrKatEngine::KeyCode::K
#define PKE_KEY_L PurrKatEngine::KeyCode::L
#define PKE_KEY_M PurrKatEngine::KeyCode::M
#define PKE_KEY_N PurrKatEngine::KeyCode::N
#define PKE_KEY_O PurrKatEngine::KeyCode::O
#define PKE_KEY_P PurrKatEngine::KeyCode::P
#define PKE_KEY_Q PurrKatEngine::KeyCode::Q
#define PKE_KEY_R PurrKatEngine::KeyCode::R
#define PKE_KEY_S PurrKatEngine::KeyCode::S
#define PKE_KEY_T PurrKatEngine::KeyCode::T
#define PKE_KEY_U PurrKatEngine::KeyCode::U
#define PKE_KEY_V PurrKatEngine::KeyCode::V
#define PKE_KEY_W PurrKatEngine::KeyCode::W
#define PKE_KEY_X PurrKatEngine::KeyCode::X
#define PKE_KEY_Y PurrKatEngine::KeyCode::Y
#define PKE_KEY_Z PurrKatEngine::KeyCode::Z
#define PKE_KEY_F1 PurrKatEngine::KeyCode::F1
#define PKE_KEY_F2 PurrKatEngine::KeyCode::F2
#define PKE_KEY_F3 PurrKatEngine::KeyCode::F3
#define PKE_KEY_F4 PurrKatEngine::KeyCode::F4
#define PKE_KEY_F5 PurrKatEngine::KeyCode::F5
#define PKE_KEY_F6 PurrKatEngine::KeyCode::F6
#define PKE_KEY_F7 PurrKatEngine::KeyCode::F7
#define PKE_KEY_F8 PurrKatEngine::KeyCode::F8
#define PKE_KEY_F9 PurrKatEngine::KeyCode::F9
#define PKE_KEY_F10 PurrKatEngine::KeyCode::F10
#define PKE_KEY_F11 PurrKatEngine::KeyCode::F11
#define PKE_KEY_F12 PurrKatEngine::KeyCode::F12
#define PKE_KEY_F13 PurrKatEngine::KeyCode::F13
#define PKE_KEY_F14 PurrKatEngine::KeyCode::F14
#define PKE_KEY_F15 PurrKatEngine::KeyCode::F15
#define PKE_KEY_F16 PurrKatEngine::KeyCode::F16
#define PKE_KEY_F17 PurrKatEngine::KeyCode::F17
#define PKE_KEY_F18 PurrKatEngine::KeyCode::F18
#define PKE_KEY_F19 PurrKatEngine::KeyCode::F19
#define PKE_KEY_F20 PurrKatEngine::KeyCode::F20
#define PKE_KEY_F21 PurrKatEngine::KeyCode::F21
#define PKE_KEY_F22 PurrKatEngine::KeyCode::F22
#define PKE_KEY_F23 PurrKatEngine::KeyCode::F23
#define PKE_KEY_F24 PurrKatEngine::KeyCode::F24
#define PKE_KEY_Apostrophe PurrKatEngine::KeyCode::Apostrophe
#define PKE_KEY_Comma PurrKatEngine::KeyCode::Comma
#define PKE_KEY_Minus PurrKatEngine::KeyCode::Minus
#define PKE_KEY_Period PurrKatEngine::KeyCode::Period
#define PKE_KEY_Slash PurrKatEngine::KeyCode::Slash
#define PKE_KEY_Semicolon PurrKatEngine::KeyCode::Semicolon
#define PKE_KEY_Equal PurrKatEngine::KeyCode::Equal
#define PKE_KEY_LeftBracket PurrKatEngine::KeyCode::LeftBracket
#define PKE_KEY_Backslash PurrKatEngine::KeyCode::Backslash
#define PKE_KEY_RightBracket PurrKatEngine::KeyCode::RightBracket
#define PKE_KEY_GraveAccent PurrKatEngine::KeyCode::GraveAccent
#define PKE_KEY_CapsLock PurrKatEngine::KeyCode::CapsLock
#define PKE_KEY_ScrollLock PurrKatEngine::KeyCode::ScrollLock
#define PKE_KEY_NumLock PurrKatEngine::KeyCode::NumLock
#define PKE_KEY_PrintScreen PurrKatEngine::KeyCode::PrintScreen
#define PKE_KEY_Pause PurrKatEngine::KeyCode::Pause
#define PKE_KEY_Keypad0 PurrKatEngine::KeyCode::Keypad0
#define PKE_KEY_Keypad1 PurrKatEngine::KeyCode::Keypad1
#define PKE_KEY_Keypad2 PurrKatEngine::KeyCode::Keypad2
#define PKE_KEY_Keypad3 PurrKatEngine::KeyCode::Keypad3
#define PKE_KEY_Keypad4 PurrKatEngine::KeyCode::Keypad4
#define PKE_KEY_Keypad5 PurrKatEngine::KeyCode::Keypad5
#define PKE_KEY_Keypad6 PurrKatEngine::KeyCode::Keypad6
#define PKE_KEY_Keypad7 PurrKatEngine::KeyCode::Keypad7
#define PKE_KEY_Keypad8 PurrKatEngine::KeyCode::Keypad8
#define PKE_KEY_Keypad9 PurrKatEngine::KeyCode::Keypad9
#define PKE_KEY_KeypadDecimal PurrKatEngine::KeyCode::KeypadDecimal
#define PKE_KEY_KeypadDivide PurrKatEngine::KeyCode::KeypadDivide
#define PKE_KEY_KeypadMultiply PurrKatEngine::KeyCode::KeypadMultiply
#define PKE_KEY_KeypadSubtract PurrKatEngine::KeyCode::KeypadSubtract
#define PKE_KEY_KeypadAdd PurrKatEngine::KeyCode::KeypadAdd
#define PKE_KEY_KeypadEnter PurrKatEngine::KeyCode::KeypadEnter
#define PKE_KEY_KeypadEqual PurrKatEngine::KeyCode::KeypadEqual
#define PKE_KEY_AppBack PurrKatEngine::KeyCode::AppBack
#define PKE_KEY_AppForward PurrKatEngine::KeyCode::AppForward
#define PKE_KEY_Oem102 PurrKatEngine::KeyCode::Oem102
#define PKE_KEY_GamepadStart PurrKatEngine::KeyCode::GamepadStart
#define PKE_KEY_GamepadBack PurrKatEngine::KeyCode::GamepadBack
#define PKE_KEY_GamepadFaceLeft PurrKatEngine::KeyCode::GamepadFaceLeft
#define PKE_KEY_GamepadFaceRight PurrKatEngine::KeyCode::GamepadFaceRight
#define PKE_KEY_GamepadFaceUp PurrKatEngine::KeyCode::GamepadFaceUp
#define PKE_KEY_GamepadFaceDown PurrKatEngine::KeyCode::GamepadFaceDown
#define PKE_KEY_GamepadDpadLeft PurrKatEngine::KeyCode::GamepadDpadLeft
#define PKE_KEY_GamepadDpadRight PurrKatEngine::KeyCode::GamepadDpadRight
#define PKE_KEY_GamepadDpadUp PurrKatEngine::KeyCode::GamepadDpadUp
#define PKE_KEY_GamepadDpadDown PurrKatEngine::KeyCode::GamepadDpadDown
#define PKE_KEY_GamepadL1 PurrKatEngine::KeyCode::GamepadL1
#define PKE_KEY_GamepadR1 PurrKatEngine::KeyCode::GamepadR1
#define PKE_KEY_GamepadL2 PurrKatEngine::KeyCode::GamepadL2
#define PKE_KEY_GamepadR2 PurrKatEngine::KeyCode::GamepadR2
#define PKE_KEY_GamepadL3 PurrKatEngine::KeyCode::GamepadL3
#define PKE_KEY_GamepadR3 PurrKatEngine::KeyCode::GamepadR3
#define PKE_KEY_GamepadLStickLeft PurrKatEngine::KeyCode::GamepadLStickLeft
#define PKE_KEY_GamepadLStickRight PurrKatEngine::KeyCode::GamepadLStickRight
#define PKE_KEY_GamepadLStickUp PurrKatEngine::KeyCode::GamepadLStickUp
#define PKE_KEY_GamepadLStickDown PurrKatEngine::KeyCode::GamepadLStickDown
#define PKE_KEY_GamepadRStickLeft PurrKatEngine::KeyCode::GamepadRStickLeft
#define PKE_KEY_GamepadRStickRight PurrKatEngine::KeyCode::GamepadRStickRight
#define PKE_KEY_GamepadRStickUp PurrKatEngine::KeyCode::GamepadRStickUp
#define PKE_KEY_GamepadRStickDown PurrKatEngine::KeyCode::GamepadRStickDown